version: '2'
# Named volumes
volumes:
  # MySQL Data
  pdh-data-data:
    driver: local
services:
  # MySQL (5.7)
  mysql:
    image: mysql:5.7
    container_name: blog-mysql
    volumes:
      - blog-data-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=blog_password
      - MYSQL_DATABASE=blog
  app:
    image: ambientum/php:7.2-nginx
    container_name: blog-app
    volumes:
      - .:/var/www/app
    ports:
      - "80:8080"
    links:
      - mysql

#  dev:
#    image: ambientum/node:9
#    container_name: pdh-npm
#    command: npm run watch-poll
#    volumes:
#      - .:/var/www/app
#    ports:
#      - 8080:8080